services:
  - type: web
    name: gta-indonesia-cirebon-multiplayer
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
